# Generated by Django 5.2.10 on 2026-01-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=100)),
                ('familyname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('is_living', models.BooleanField()),
                ('death_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.trees')),
            ],
        ),
    ]
