# Generated by Django 5.2.10 on 2026-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
